<?xml version="1.0" encoding="UTF-8"?><testrun name="AccountControllerTest" project="ABCBankingUserr" tests="3" started="3" failures="3" errors="0" ignored="0">
  <testsuite name="com.example.controller.AccountControllerTest" time="0.456" displayname="AccountControllerTest" uniqueid="[engine:junit-jupiter]/[class:com.example.controller.AccountControllerTest]">
    <testcase name="testAdd" classname="com.example.controller.AccountControllerTest" time="0.348" displayname="testAdd()" uniqueid="[engine:junit-jupiter]/[class:com.example.controller.AccountControllerTest]/[method:testAdd()]">
      <failure>
        <expected>com.example.service.AccountService#0 bean.createAccount(
    com.example.model.Account@22eccd2c
);</expected>
        <actual>com.example.service.AccountService#0 bean.createAccount(
    com.example.model.Account@2114955c
);
</actual>
        Argument(s) are different! Wanted:
com.example.service.AccountService#0 bean.createAccount(
    com.example.model.Account@22eccd2c
);
-&gt; at com.example.service.AccountService.createAccount(AccountService.java:19)
Actual invocations have different arguments:
com.example.service.AccountService#0 bean.createAccount(
    com.example.model.Account@2114955c
);
-&gt; at com.example.controller.AccountController.createAccount(AccountController.java:21)
&#13;
	at com.example.service.AccountService.createAccount(AccountService.java:19)&#13;
	at com.example.controller.AccountControllerTest.testAdd(AccountControllerTest.java:95)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
    <testcase name="testRead" classname="com.example.controller.AccountControllerTest" time="0.088" displayname="testRead()" uniqueid="[engine:junit-jupiter]/[class:com.example.controller.AccountControllerTest]/[method:testRead()]">
      <failure>java.lang.AssertionError: No value at JSON path "$[0].name"&#13;
	at org.springframework.test.util.JsonPathExpectationsHelper.evaluateJsonPath(JsonPathExpectationsHelper.java:302)&#13;
	at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:99)&#13;
	at org.springframework.test.web.servlet.result.JsonPathResultMatchers.lambda$value$2(JsonPathResultMatchers.java:111)&#13;
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)&#13;
	at com.example.controller.AccountControllerTest.testRead(AccountControllerTest.java:72)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
Caused by: com.jayway.jsonpath.PathNotFoundException: No results for path: $[0]['name']&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testreadOne" classname="com.example.controller.AccountControllerTest" time="0.016" displayname="testreadOne()" uniqueid="[engine:junit-jupiter]/[class:com.example.controller.AccountControllerTest]/[method:testreadOne()]">
      <failure>java.lang.AssertionError: Status expected:&lt;200&gt; but was:&lt;404&gt;&#13;
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)&#13;
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)&#13;
	at org.springframework.test.web.servlet.result.StatusResultMatchers.lambda$matcher$9(StatusResultMatchers.java:637)&#13;
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)&#13;
	at com.example.controller.AccountControllerTest.testreadOne(AccountControllerTest.java:82)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
